version: "3"
# General
# 2020-07-31
# Web server
## Nginx
services:
    web:
        image: nginx:1.19.1-alpine
        container_name: phpserver_nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./server/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        build:
            context: .
        container_name: phpserver_phpfpm
        volumes:
            - ./www:/www
        links:
            - mariadb
    mariadb:
        image: yobasystems/alpine-mariadb:10.4.13
        container_name: phpserver_mariadb
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: hguyFtgfR4r9R4r76
            MYSQL_USER: jorge
            MYSQL_PASSWORD: hguyFt6S95dgfR4ryb
            # Not used
            # MYSQL_DATABASE: specify the name of the database
            # MYSQL_CHARSET: default charset (utf8) for Mariadb
            # MYSQL_COLLATION: default collation (utf8_general_ci)