version: "3"
services:
    web:
        image: nginx:1.19.1-alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: php:7.4.8-fpm-alpine3.12
        container_name: php-fpm
        volumes:
            - ./www:/www
        links:
            - db
    db:
        image: mariadb:10.5.4-focal
        container_name: mariadb
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=teste