version: "3"
services:
    web:
        image: nginx:1.19.1-alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        build:
            context: .
        container_name: php-fpm
        volumes:
            - ./www:/www
        links:
            - db
    db:
        image: mariadb:10.5.4-focal
        container_name: mariadb
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=teste
            - MYSQL_USER=jorge
            - MYSQL_PASSWORD=hguyFt6S95dgfR4ryb
            # Not used
            # MYSQL_DATABASE: specify the name of the database
            # MYSQL_CHARSET: default charset (utf8) for Mariadb
            # MYSQL_COLLATION: default collation (utf8_general_ci)